# Instalasi

In [ ]:
!pip install numpy

# Dimensi dalam Array

- Dimensi dalam array adalah satu tingkat kedalaman array (array bersarang).
- array bersarang: adalah array yang memiliki array sebagai elemennya.

In [ ]:
import numpy as np

## Array 0 Dimensi (0D)

Array 0-D, atau **Skalar**, adalah elemen dalam array. Setiap nilai dalam array adalah array 0-D.

In [ ]:
# array 0 Dimensi
arr = np.array(42)
print(arr)

42


## Array 1 Dimensi (1D)

Array dengan 1 dimensi (**vektor**) adalah array yang hanya memiliki satu sumbu (axis). Biasanya array ini disebut sebagai vektor karena elemen-elemennya hanya tersusun dalam satu baris.

In [ ]:
# Membuat array satu dimensi
arr1 = np.array([1, 2, 3, 4])
print(arr1)

[1 2 3 4]


## Array 2 Dimensi (2D)

Array dengan 2 dimensi adalah array yang memiliki dua sumbu (axis), seperti **matriks**. Dalam hal ini, array terdiri dari beberapa baris dan kolom.

In [ ]:
# Membuat array 2D
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Array 3 Dimensi (3D)

Array dengan 3 dimensi adalah array yang memiliki tiga sumbu. Array 3D memiliki "kedalaman" selain baris dan kolom.

In [ ]:
# Membuat array 3D
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# ndim & ndmin

NumPy Arrays menyediakan ***ndim*** atribut yang mengembalikan bilangan bulat yang memberi tahu kita berapa banyak dimensi yang dimiliki array.

In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


Sebuah array dapat memiliki sejumlah dimensi.

Saat array dibuat, Anda dapat menentukan **jumlah dimensi** dengan menggunakan ***ndmin*** argumen.

In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# zeros, empty & random

In [ ]:
print(np.zeros(6), "\n")
# print(np.ones(6),"\n")

#membuat array yang konten awalnya acak dan bergantung pada status memori.
print(np.empty(6))

b = np.empty(2, dtype = int)
print("Matrix b : \n", b)

a = np.empty([2, 2], dtype = int)
print("\nMatrix a : \n", a)

c = np.empty([3, 3])
print("\nMatrix c : \n", c)

[0. 0. 0. 0. 0. 0.] 

[0. 0. 0. 0. 0. 0.]
Matrix b : 
 [-9093133594791772939      132845646004120]

Matrix a : 
 [[     36405337             0]
 [5063766443163  103079215124]]

Matrix c : 
 [[1.846021e-316 0.000000e+000 0.000000e+000]
 [0.000000e+000 0.000000e+000 0.000000e+000]
 [0.000000e+000 0.000000e+000 0.000000e+000]]


In [ ]:
# contoh random
print(np.random.random(6))

[0.48863384 0.25685633 0.09760186 0.87496104 0.0210428  0.2826921 ]


In [ ]:
# random normal untuk membuar distribusi normal
print(np.random.normal(0, 1, 6))

[ 1.63301664  0.77722507  2.35485844 -0.1308518  -0.20109293  1.11306569]


In [ ]:
# random uniform untuk membuar distribusi uniform
print(np.random.uniform(0, 1, 6))

[0.02459463 0.48532022 0.28642348 0.09583729 0.99328257 0.14348315]


In [ ]:
# choice untuk memilih item tertentu secara acak dari beberapa item
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10))

['i' 'a' 'i' 'o' 'i' 'e' 'a' 'u' 'e' 'u']


# Slicing dan Indeksasi

Slicing memungkinkan kita untuk mengambil bagian tertentu dari array.

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# Mengambil elemen mulai dari index 1 hingga 3
sliced_arr = arr[1:4]
print(sliced_arr)  # Output: [20 30 40]


[20 30 40]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


Misalkan Anda memiliki code berikut:
```
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
```

sekarang tugas Anda adalah memilih elemen-elemen dari array tersebut yang berada pada baris ke-2 (indeks 1) dan kolom ke-2 hingga kolom ke-4 (indeks 1 hingga 3, ingat bahwa Python menggunakan indexing berbasis nol).

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Mengambil baris pertama
first_row = arr_2d[0]
print(first_row)  # Output: [1 2 3]

[1 2 3]


In [ ]:
arr = np.array([1, 2, 3, 4])

# Dapatkan elemen ketiga dan keempat dari array dan tambahkan keduanya.
print(arr[2] + arr[3])

7


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])

2nd element on 1st dim:  2


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [ ]:
# akses elemen ke-3 dari array ke-2 dari array ke-1
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1, 0, 2])

9


# Copy & View

Perbedaan utama antara **Copy** dan **View** array adalah bahwa **copy** adalah membuat array baru, dan **view** hanyalah tampilan array aslinya.


**View** adalah referensi ke array asli, artinya array view akan berbagi data dengan array asli. Jika Anda mengubah nilai dalam array view, nilai tersebut juga akan berubah di array asli, dan sebaliknya. Dengan kata lain, view tidak membuat salinan baru dari data; hanya memberikan "pandangan" atau "referensi" terhadap data yang ada.

Ciri-ciri View:
- View mengakses data yang sama dengan array asli.
- Perubahan pada view akan mempengaruhi array asli.
- Memiliki efisiensi memori yang lebih tinggi karena tidak menyalin data.

In [ ]:
import numpy as np

# Membuat array asli
arr = np.array([1, 2, 3, 4, 5])

# Membuat view (referensi) ke array
view_arr = arr[1:4]

# Menampilkan array asli dan view
print("Array Asli:", arr)
print("Array View:", view_arr)

# Mengubah nilai pada view
view_arr[0] = 99

# Menampilkan array setelah perubahan pada view
print("\nSetelah mengubah view:")
print("Array Asli:", arr)  # Array asli berubah
print("Array View:", view_arr)


Array Asli: [1 2 3 4 5]
Array View: [2 3 4]

Setelah mengubah view:
Array Asli: [ 1 99  3  4  5]
Array View: [99  3  4]


**Copy** adalah salinan independen dari array asli. Saat Anda membuat salinan dari sebuah array menggunakan metode copy(), NumPy membuat salinan baru dari data. Artinya, perubahan pada salinan tidak akan mempengaruhi array asli dan sebaliknya.

Ciri-ciri Copy:
- Copy membuat salinan terpisah dari data asli.
- Perubahan pada copy tidak mempengaruhi array asli.
- Menggunakan lebih banyak memori karena data disalin.

In [ ]:
import numpy as np

# Membuat array asli
arr = np.array([1, 2, 3, 4, 5])

# Membuat salinan array (copy)
copy_arr = arr[1:4].copy()

# Menampilkan array asli dan salinan
print("Array Asli:", arr)
print("Array Copy:", copy_arr)

# Mengubah nilai pada copy
copy_arr[0] = 99

# Menampilkan array setelah perubahan pada copy
print("\nSetelah mengubah copy:")
print("Array Asli:", arr)  # Array asli tidak berubah
print("Array Copy:", copy_arr)


Array Asli: [1 2 3 4 5]
Array Copy: [2 3 4]

Setelah mengubah copy:
Array Asli: [1 2 3 4 5]
Array Copy: [99  3  4]


#Array Shape



Array NumPy memiliki atribut yang disebut ***shape*** yang mengembalikan tuple dengan setiap indeks memiliki jumlah elemen yang sesuai.

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


#NumPy Array Reshaping





- Reshaping berarti mengubah bentuk array.
- Bentuk array adalah jumlah elemen dalam setiap dimensi.
- Dengan membentuk kembali (reshaping) kita dapat menambah atau menghapus dimensi atau mengubah jumlah elemen di setiap dimensi.

Reshape Array 1D menjadi 2D:


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
reshaped_arr = arr.reshape(3, 4)
print(reshaped_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Reshape Array 2D menjadi 1D:

In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reshaped_arr = arr_2d.reshape(-1)
print(reshaped_arr)

[1 2 3 4 5 6 7 8 9]


Reshape dengan Dimensi yang Tidak Sesuai:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
try:
    reshaped_arr = arr.reshape(2, 4)
    print(reshaped_arr)
except ValueError as e:
    print(f"Error: {e}")


Error: cannot reshape array of size 6 into shape (2,4)


# Unknown Dimension

Anda diperbolehkan memiliki satu dimensi "tidak diketahui".

Artinya Anda tidak perlu menentukan angka pasti untuk salah satu dimensi dalam metode reshape.


Contoh, konversi array 1D dengan 8 elemen ke array 3D dengan elemen 2x2:

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Flattening & Ravel

Flattening array berarti mengubah array multidimensi menjadi array 1D.

Kita bisa gunakan reshape(-1)untuk melakukan ini.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


Fungsi **flatten()** adalah fungsi yang digunakan untuk mengubah array dengan dimensi lebih tinggi (seperti array 2D, 3D, dll.) menjadi array 1D (vektor). Fungsi ini mengembalikan salinan baru dari array yang telah "datar" atau satu dimensi, tanpa memodifikasi array asli.

syntax:
```
numpy.ndarray.flatten(order='C')
```

Parameter:

- order: Opsional, menentukan urutan pengurutan elemen saat meratakan array.
  - 'C': Pengurutan baris per baris (default).
  - 'F': Pengurutan kolom per kolom (mirip dengan kolom dalam bahasa Fortran).



In [ ]:
arr = np.array([
    [1, 2, 3],
     [4, 5, 6]
 ])
newarr = arr.flatten()
print(newarr)

[1 2 3 4 5 6]


In [ ]:
arr = np.array([
    [1, 2, 3],
     [4, 5, 6]])
newarr = arr.flatten(order='F')
print(newarr)

[1 4 2 5 3 6]


**ravel()** adalah fungsi yang digunakan untuk mengubah array multidimensi menjadi array 1D, mirip dengan flatten(). Namun, ada perbedaan penting antara keduanya, yaitu terkait dengan salinan data.

- ravel() mengembalikan view (referensi) dari array yang telah diratakan, jika memungkinkan. Artinya, jika array tersebut tidak membutuhkan alokasi ulang memori (misalnya, array sudah dalam bentuk yang dapat diratakan secara langsung), maka ravel() akan mengembalikan referensi ke data asli, bukan salinan baru.

- flatten(), di sisi lain, selalu mengembalikan salinan baru dari array yang diratakan, sehingga perubahan pada array hasil ravel() atau array asli dapat mempengaruhi data yang sama jika ravel() mengembalikan view, sementara perubahan pada hasil flatten() tidak akan mempengaruhi array asli.

syntax:
```
numpy.ndarray.ravel(order='C')
```

Parameter:

- order: Opsional, menentukan urutan pengurutan elemen saat meratakan array.
  - 'C': Pengurutan baris per baris (default).
  - 'F': Pengurutan kolom per kolom (mirip dengan kolom dalam bahasa Fortran).


In [ ]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
print(np.ravel(x))
print(np.ravel(x, order='F'))
print(np.ravel(x, order='C'))

[1 2 3 4 5 6]
[1 4 2 5 3 6]
[1 2 3 4 5 6]


# Broadcasting

Broadcasting adalah cara untuk melakukan operasi pada array yang memiliki bentuk atau dimensi yang berbeda.



In [ ]:
arr = np.array([1, 2, 3])

# Penambahan array scalar
result = arr + 10
print(result)  # Output: [11 12 13]


[11 12 13]


Penjumlahan Array 1D dengan Array 2D:

In [ ]:
import numpy as np

arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[4, 5, 6], [7, 8, 9]])

result = arr_1d + arr_2d
print(result)


[[ 5  7  9]
 [ 8 10 12]]


Pengurangan Array 2D dengan Array 1D:

In [ ]:
arr_2d = np.array([[10, 20, 30], [40, 50, 60]])
arr_1d = np.array([1, 2, 3])

result = arr_2d - arr_1d
print(result)


[[ 9 18 27]
 [39 48 57]]


# Matriks

Ingatlah aturan berikut ketika melakukan operasi matriks:
- Untuk melakukan penjumlahan matriks atau pengurangan matriks, dua matriks harus memiliki ukuran (dimensi) yang sama. Artinya, jumlah baris dan jumlah kolom kedua matriks harus identik.
- Untuk perkalian matriks, syarat yang harus dipenuhi adalah jumlah kolom pada matriks pertama harus sama dengan jumlah baris pada matriks kedua.


In [ ]:
import numpy as np

A = np.array([
    [1, 2, 3],
     [4, 5, 6]
    ])

B = np.array([
    [7, 8, 9],
     [10, 11, 12]
    ])

result = A + B
print(result)

[[ 8 10 12]
 [14 16 18]]


In [ ]:
result = A - B
print(result)

[[-6 -6 -6]
 [-6 -6 -6]]


In [ ]:
result = A / B
print(result)

[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [ ]:
result = A * B
print(result)

[[ 7 16 27]
 [40 55 72]]


## Dot Product

Untuk **dot product** (perkalian titik) antara dua matriks di NumPy, kita dapat menggunakan fungsi `np.dot()` atau operator `@`. **Dot product** untuk dua matriks \( A \) dan \( B \) dapat dilakukan jika jumlah kolom matriks pertama (A) sama dengan jumlah baris matriks kedua (B).

Jika kita ingin menghitung **dot product** antara dua matriks **A** dan **B**, kita harus memastikan bahwa jumlah kolom pada matriks pertama (A) sama dengan jumlah baris pada matriks kedua (B). Dalam contoh yang Anda berikan, kedua matriks A dan B memiliki dimensi \( 2 \times 3 \), yang berarti mereka tidak dapat langsung dikalikan menggunakan dot product standar, karena kolom A (3) tidak sama dengan baris B (2).

Namun, jika kita ingin melakukan **dot product** dengan cara yang benar, kita dapat mengubah dimensi matriks tersebut agar memenuhi syarat atau melakukan perkalian antara dua matriks dengan dimensi yang sesuai.




**Contoh: Dot Product Matriks yang Sesuai**

Jika matriks A adalah ( 2 * 3 ) dan matriks B adalah ( 3 * 2 ), maka hasil dot product akan menghasilkan matriks ( 2 * 2 ).

In [ ]:
import numpy as np

# Matriks A berukuran 2x3
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Matriks B berukuran 3x2
B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

# Perkalian dot product
result = np.dot(A, B)
# Alternatif: result = A @ B

print(result)

[[ 58  64]
 [139 154]]


# Perhitungan Dengan Formula

In [ ]:
import numpy as np

# Array data
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Perhitungan Mean
mean = np.mean(data)
print("Mean (Rata-rata):", mean)

Mean (Rata-rata): 5.5


In [ ]:
# Perhitungan Median
median = np.median(data)
print("Median:", median)


Median: 5.5


**Contoh : Hitung Accuracy dalam pada model prediksi**

Akurasi (accuracy) digunakan untuk mengukur seberapa baik model dalam memprediksi label yang benar. Rumus untuk menghitung akurasi adalah:

$$
\text{Accuracy} = \frac{\text{Jumlah Prediksi yang Benar}}{\text{Total Jumlah Data}}
$$

Dimana:
- **Jumlah Prediksi yang Benar** adalah jumlah data yang diprediksi dengan benar oleh model (True Positives dan True Negatives).
- **Total Jumlah Data** adalah jumlah keseluruhan data yang digunakan dalam prediksi.

In [ ]:
# Prediksi model
predictions = np.array([1, 0, 1, 1, 0, 1, 0, 0])

# Label asli
labels = np.array([1, 0, 0, 1, 0, 1, 1, 0])

# Menghitung jumlah prediksi yang benar
correct_predictions = np.sum(predictions == labels)

# Menghitung total jumlah data
total_data = len(labels)

# Menghitung akurasi
accuracy = correct_predictions / total_data
print(f"Accuracy: {accuracy:.2f}")


Accuracy: 0.75


# Latihan

1. Buatlah fungsi untuk menentukan nilai maksimum dan minimum dalam Array berikut:
```
data = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
```


2. Buatlah sebuah fungsi yang menerima array 1D dan menghitung rata-rata hanya untuk angka positif dalam array tersebut. Jika tidak ada angka positif, kembalikan nilai None. Misalkan:
  ```
  data = np.array([-1, 2, 3, -4, 5, -6])
  ```

  output yang diharapkan:
  ```
  Average of Positive Numbers: 3.3333333333333335
  ```


3. Buatlah sebuah fungsi yang menerima array 1D dan angka target, lalu mengembalikan nilai yang paling dekat dengan target tersebut.

  Petunjuk:
  - Gunakan perbedaan absolut untuk menghitung jarak antara angka target dan setiap elemen dalam array.
  - Temukan nilai yang memiliki jarak terdekat dengan target.

  Misalkan datanya:
  ```
  data = np.array([1, 3, 7, 8, 12])
  target_value = 6
  ```
  output yang diharapkan:
  ```
  The closest value to 6 is 7
  ```