# Numpy

Numpy adalah package Python yang umumnya digunakan untuk manipulasi angka, tipe data numeric.

Numerical Python (Numpy) dan biasanya disingkat lagi jadi "np"


In [1]:
import numpy as np

selain function2 yang memudahkan kalkulasi matematik, Numpy juga punya tipe data yang memudahkan matematik

Numpy Array

mirip list tapi dia banyak bawaan fungsionalitas yang berasumsi isinya angka semua


In [2]:
a = [1, 2, 3]
b = [4, 5, 6]

# nambahkan list ke list
a + b

[1, 2, 3, 4, 5, 6]

In [ ]:
# kalau pakai numpy array

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# nambah array ke array
a + b



array([5, 7, 9])

CRUD - Create Read Update Delete

## Create

cara membuat numpy array


In [4]:
# 1. ubah list jadi numpy array dengan function np.array()

a = np.array([1, 2, 3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [58]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np
a = np.array([42])
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

1
1
2
3


In [7]:
# 2. kita bisa buat numpy array yang isinya angka 1 semua

b = np.ones(3)
print(b)
print(type(b))

[1. 1. 1.]
<class 'numpy.ndarray'>


In [7]:
b2 = np.ones((3, 4)) * 3
print(b2)

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In [9]:
# 2b. kita bisa buat numpy array yang isinya angka 0 semua

b = np.zeros(5)
print(b)
print(type(b))

[0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


In [62]:
b2 = np.zeros((5, 3)) + 8
print(b2)

[[8. 8. 8.]
 [8. 8. 8.]
 [8. 8. 8.]
 [8. 8. 8.]
 [8. 8. 8.]]


In [12]:
# 3. kita bisa buat numpy array yang isinya angka urut, kayak range

# 5 angka dari 0 +1 +1 sampai ada 5 angka
c = np.arange(5)
print(c)

# start, end, incrementnya +1
c = np.arange(18, 30)
print(c)

# start, end, increment
c = np.arange(3000, -3000, -800)
print(c)

[0 1 2 3 4]
[18 19 20 21 22 23 24 25 26 27 28 29]
[ 3000  2200  1400   600  -200 -1000 -1800 -2600]


In [10]:
c2 = np.arange(6).reshape((3, 2))
print(c2)

print("---")

# start end increment
c2 = np.arange(17, 110, 17).reshape((3, 2))
print(c2)

[[0 1]
 [2 3]
 [4 5]]
---
[[ 17  34]
 [ 51  68]
 [ 85 102]]


In [12]:
# untuk latihan biasanya kita suka bikin2 angka random
# 4. kita pakai randomizer

d = np.random.random(10)
print(d)


j = np.random.random (10)
print(j)

[0.71399574 0.43915224 0.47267952 0.1975985  0.20339029 0.49806994
 0.10573299 0.98400276 0.56927965 0.83170109]
[0.44620537 0.24464018 0.91272691 0.73276779 0.35807179 0.70175911
 0.83361041 0.67555375 0.65805574 0.05413458]


In [72]:
d2 = np.random.random(10).reshape((2, 5))
print(d2)

[[0.73408928 0.09687259 0.41314339 0.56006812 0.63631171]
 [0.18603733 0.188702   0.77935335 0.72719524 0.70193587]]


dia akan buatkan angka random antara 0 dan 1

tapi angka antara 0 dan 1 ini kan jarang kita perlukan, biasanya kita mau test buat data random spesifik.

kita bisa pakai teknik "broadcast" dan just roundup/ roundown untuk membuat dataset yang kita mau


In [18]:
(d + 20) * 3

array([62.26155874, 60.75833117, 62.78498697, 61.53242719, 62.09819513,
       62.1339106 , 62.22731387, 61.31383255, 60.36948883, 60.46042581])

In [19]:
# contoh, dataset hasil lempar dadu (1-6) 100x

#dadu100 = ((np.random.random(100) * 6) + 1).astype(int)
dadu100 = (np.random.random(100) *6 + 1).astype(int)
dadu100

array([3, 1, 5, 1, 4, 5, 4, 3, 6, 5, 4, 2, 2, 6, 3, 6, 4, 4, 6, 3, 4, 2,
       5, 6, 3, 3, 3, 6, 1, 1, 4, 3, 4, 4, 4, 6, 1, 6, 5, 2, 6, 5, 1, 4,
       2, 6, 3, 2, 6, 3, 1, 2, 1, 6, 5, 2, 1, 6, 4, 5, 4, 5, 3, 4, 6, 5,
       6, 3, 4, 5, 1, 6, 4, 3, 2, 3, 3, 5, 5, 5, 3, 3, 6, 4, 6, 2, 3, 3,
       6, 1, 5, 2, 6, 4, 3, 5, 3, 3, 4, 1])

selain random.random kita bisa juga generate data dummy seperti ini dengan distribusi data tipe lain misalnya normal distribution


## Read

kita bisa ambil data dari numpy array menggunakan:

- indexing (ambil 1 angka dengan 1 index)
- slicing (ambil beberapa angka dengan beberapa index)


In [20]:
# kita mau ambil hasil lempar dadu ke-10
dadu100[9]

np.int64(5)

In [21]:
# kita mau ambil hasil lempar dadu ke-10,20,30,40,50
dadu100[[9, 19, 29, 39, 49]]

array([5, 3, 1, 2, 3])

In [22]:
# untuk slicing kita bisa pakai range kalau kita punya pattern tertentu
dadu100[range(9, 50, 10)]

array([5, 3, 1, 2, 3])

In [23]:
# kalau mau ambil beberapa item yang urut juga bisa
# misalnya hasil lempar ke 3-8
dadu100[2:8]

array([5, 1, 4, 5, 4, 3])

# Numpy array 2D

create dan read

- cek jumlah dimensi, "shape", "ndim"
- cek total item dalam array, "size"
- jadi perlu 2 set index untuk indexing dan slicing
- ubah dari 1D ke 2D dan sebaliknya kita gunakan "reshape"


In [24]:
# mau buat hasil lempar dadu 10x oleh 3org berbeda
# 3 row, 10 column

dadu3 = ((np.random.random(30) * 6) + 1).astype(int)
dadu3 = dadu3.reshape((3, 10))
dadu3

array([[2, 1, 6, 1, 6, 5, 2, 6, 2, 5],
       [4, 2, 2, 5, 6, 3, 5, 1, 3, 5],
       [1, 5, 2, 1, 3, 6, 4, 2, 4, 2]])

In [25]:
# shape, ndim, size
print(dadu3.shape, "(jumlah_row, jumlah_col)")
print(dadu3.ndim, "jumlah dimensi np array ini")
print(dadu3.size, "jumlah item dalam np array ini")

(3, 10) (jumlah_row, jumlah_col)
2 jumlah dimensi np array ini
30 jumlah item dalam np array ini


In [26]:
# indexing dan slicing

# ambil hasil lempar dadu orang ke-3, lemparan ke-8
dadu3[(2, 7)]
dadu3[2, 7]

# index 1 item di numpy array 2D bentuknya jadi tuple (row, col)

np.int64(2)

In [27]:
# ambil hasil lempar dadu semua orang, lemparan ke-8
dadu3[:, 7]
dadu3[0:4, 7]

array([6, 1, 2])

In [28]:
dadu3

array([[2, 1, 6, 1, 6, 5, 2, 6, 2, 5],
       [4, 2, 2, 5, 6, 3, 5, 1, 3, 5],
       [1, 5, 2, 1, 3, 6, 4, 2, 4, 2]])

In [29]:
# hasil lempar dadu orang ke 1 dan 2 (row 0 dan 1), lemparan ke 8 dan 9 (col 7 dan 8)
dadu3[0:2, 7:9]

array([[6, 2],
       [1, 3]])

## Operations

Membuat kalkulasi matematik dengan numpy array

Misalnya kita punya stok barang dan harga beli, harga jual, kita mau hitung profit


In [48]:
n_stok = np.array([10, 30, 4, 12, 5, 8])
n_beli = np.arange(1000, 7000, 1000)
n_jual = n_beli * 1.3

print(n_stok)
print(n_beli)
print(n_jual)

[10 30  4 12  5  8]
[1000 2000 3000 4000 5000 6000]
[1300. 2600. 3900. 5200. 6500. 7800.]


In [50]:
# hitung profit per penjualan
n_profit_per_item = n_jual - n_beli
n_profit_per_item

array([ 300.,  600.,  900., 1200., 1500., 1800.])

In [ ]:
# kalau terjual habis
total_profit = n_profit_per_item * n_stok
total_profit.sum()  # total

60900.0

In [ ]:
# rata-rata
total_profit.mean()

10150.0

In [55]:
print(total_profit.min(), total_profit.max())

3000.0 18000.0


In [56]:
np.median(total_profit)

10950.0

## Matrices

Numpy array 2 dimensi dimana setiap row punya jumlah kolom yang sama (tidak bolong bolong) dan tentu isinya angka semua

contoh: https://docs.google.com/spreadsheets/d/1s9IpaaXUrYPHcni8daiplru8zly1mtn67CIMmUb15aQ/edit?usp=sharing

dot product: https://www.mathsisfun.com/algebra/matrix-multiplying.html


In [75]:
# dot product
m_roti = np.array([[5, 3, 7],
                   [10, 1, 2]])
m_hargaroti = np.array([2000, 3000, 1500]).reshape((3, 1))

m_roti

array([[ 5,  3,  7],
       [10,  1,  2]])

In [76]:
m_hargaroti

array([[2000],
       [3000],
       [1500]])

In [77]:
m_roti.dot(m_hargaroti)

array([[29500],
       [26000]])

total penjualan senin 29500, selasa 26000


## Latihan


In [78]:
import numpy as np

data = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
max(data)

9

In [79]:
data.max()

9

In [80]:
data.min()

1